application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      aem-sfcc:
        license: Apache-2.0
        actions:
          render-page:
            function: actions/render-page/index.js
            web: 'yes'
            runtime: nodejs:14
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          run-diff:
            function: actions/run-diff/index.js
            web: 'yes'
            runtime: nodejs:14
            inputs:
              LOG_LEVEL: debug
              USERNAME: $USERNAME
              PASSWORD: $PASSWORD
            annotations:
              require-adobe-auth: false
              final: true
